---
# - name: Install browsers
#   become: true
#   community.general.pacman:
#     name:
#       - opera
#       - opera-ffmpeg-codecs

- name: Install helpers
  aur:
    name: [yt-dlp-ejs, yt-dlp-drop-in]
