---
- any_errors_fatal: true
  hosts: all
  roles:
    - x/kde
    - has/aur/apps/must-have
    - has/aur/app/google-chrome
    - has/app/snapper
    - has/apps/browser
    - has/apps/encryption
    - has/apps/media
    - has/apps/network
    - has/apps/viewer
    - has/device/network
    - has/device/video
    - has/device/yubikey
