---
- any_errors_fatal: true
  name: Deploy SSH Host Certificates
  hosts: all
  become: true
  vars:
    ca_key_path: ~/.ssh/id_ed25519_sk_rk_29526146:ca-hosts
    rotation_threshold_days: 30  # Actual key rotation frequency
  roles: [has/signed-ssh-host-key]
